web/myhome/urls.py
# from django.contrib import admin
from django.urls import path
from .views import *

urlpatterns = [
    # path('admin/', admin.site.urls),
    #首页
    path('', IndexViews.index,name='myhome_index'),
    path('booklist/<int:typeid>', IndexViews.booklist,name='myhome_booklist'),
    path('detail/<int:bookid>', IndexViews.detail,name='myhome_bookdetail'),
    path('search', IndexViews.booksearch,name='myhome_booksearch'),

    # 购物车列表页
    path('cart/index', CartViews.index,name='myhome_cartindex'),
    path('cart/addcart', CartViews.addcart,name='myhome_addcart'),
    path('cart/delcart', CartViews.delcart,name='myhome_delcart'),
    path('cart/modicart', CartViews.modicart,name='myhome_modicart'),

    # 收货地址
    path('address/add', AddressViews.addaddress,name='myhome_address_add'),
    path('address/modi', AddressViews.modiaddress,name='myhome_address_modi'),
    path('address/del', AddressViews.deladdress,name='myhome_address_del'),

    #用户个人信息管理  #支付成功后的跳转地址
    path('userinfo/index', UserinfoViews.index,name='myhome_userinfo'),
    path('userinfo/modiuser', UserinfoViews.modiuser,name='myhome_modiuser'),


    path('userinfo/seeorder/<int:id>', UserinfoViews.seeorder,name='myhome_seeorder'),
    path('userinfo/delitem', UserinfoViews.delitem,name='myhome_delitem'),




    #订单
    path('order/confirm', OrderViews.confirm,name='myhome_confirm'),
    path('order/create', OrderViews.create,name='myhome_order_create'),

    #发起支付请求
    path('order/buy', OrderViews.buypay,name='myhome_order_pay'),
    #回调函数
    path('order/pay_result', OrderViews.pay_result,name='myhome_pay_result'),
     path('order/pay_get', OrderViews.pay_get,name='myhome_pay_get'),


    # path('order/list', OrderViews.mylist,name='myhome_order_list'),


    #登录
    path('login', LoginViews.login,name='myhome_login'),
    path('dologin',LoginViews.dologin,name='myhome_dologin'),
    #注销
    path('logout', LoginViews.logout,name='myhome_logout'),

    #注册
    path('register', RegisterViews.register,name='myhome_register'),
    path('doregister',RegisterViews.doregister,name='myhome_doregister'),

    #检测手机号
    path('checkphone',RegisterViews.checkphone,name='myhome_checkphone'),

    #给手机发送验证码，并返回信息给用户
    path('sendphone', RegisterViews.sendphone,name='myhome_sendphone'),
    path('sendcode', RegisterViews.SendCode,name='myhome_sendcode'),
   
]

web/web/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    #特有的后台地址
    # path('admin/', admin.site.urls),
    #后台
    path('myadmin/', include('myadmin.urls')),
    #前台
    path('', include('myhome.urls')),
    #富文本编辑器
    path('ueditor/', include('ueditor.urls')),
]

web/myadmin/models.py
from django.db import models

# Create your models here.

#会员类 包括前台用户所有的信息
class Users(models.Model):
    #主要信息
    phone=models.CharField(max_length=11,unique=True)#s手机号
    password=models.CharField(max_length=80)#密码
    face=models.CharField(max_length=100,default="/static/myadmin/assets/img/user06.png")#头像
    #次要信息
    nickname=models.CharField(max_length=20,null=True)#昵称
    homeaddress=models.CharField(max_length=100,null=True)#居住地
    sex=models.CharField(max_length=6,null=True)#性别
    usertype=models.CharField(max_length=1,null=True)#身份类别
    createtime=models.DateTimeField(auto_now_add=True)#创建时间
    isdel=models.CharField(max_length=10,default='004001')#是否删除
    #自定义用户权限
    class Meta:
        permissions = (
            ("show_Users", "查看用户列表"),
            ("create_Users", "添加用户"),
            ("edit_Users", "修改用户"),
            ("remove_Users", "删除用户"),
        )

#图书分类类
class Booktype(models.Model):
    catename=models.CharField(max_length=20)#分类名
    pid=models.IntegerField()#父级id
    path=models.CharField(max_length=50)#path路径
#自定义商品分类权限
    class Meta:
        permissions = (
            ("show_Booktype", "查看图书分类列表"),
            ("create_Booktype", "添加图书分类"),
            ("edit_Booktype", "修改图书分类"),
            ("remove_Booktype", "删除图书分类"),
        )

#图书类
class Books(models.Model):
    typeid=models.ManyToManyField(to="Booktype")#图书类别id 用作外键联系类别类
    bookname=models.CharField(max_length=70) #图书名称
    recommend=models.CharField(max_length=255,null=True) #推荐语
    author=models.CharField(max_length=50) #作者
    publisher=models.CharField(max_length=150) #出版社
    pdate=models.DateField() #出版时间
    price=models.DecimalField(max_digits=5,decimal_places=2) #价格
    num=models.IntegerField()#库存
    isbn=models.CharField(max_length=13)# 国际书号isbn
    bookdetail=models.TextField(null=True) #商品详情
    cate=models.CharField(max_length=1,default='0') #0上架 1热卖 2促销  3推荐 4下架
    isdel=models.CharField(max_length=6,default="004001") #是否逻辑删除  004001可用  004002不可用
#自定义图书权限
    class Meta:
        permissions = (
            ("show_Books", "查看图书列表"),
            ("create_Books", "添加图书"),
            ("edit_Books", "修改图书"),
            ("remove_Books", "删除图书"),
        )

##图集
class Bookimgs(models.Model):
    img_url=models.ImageField(upload_to="static/myadmin/book_img/")#图书图片地址
    bookid=models.ForeignKey('Books',on_delete=models.CASCADE)#图书id  用来联系图书类


#购物车
class Cart(models.Model):
    #用户ID
    # 商品id
    # 数量
    # 是否选中
    uid=models.ForeignKey('Users',on_delete=models.CASCADE) #会员id  当做外键  用来联系用户类
    bookid=models.ForeignKey('Books',on_delete=models.CASCADE)#图书id 当做外键  用来联系图书类
    num=models.IntegerField()#图书商品的数量
    select=models.IntegerField(default=0)#0未选中  1选中
    # 前端业务的数据是可以被修改的，所以前端价格不能获取，展出的数据不一定真，能用id获取就不要用其他地方获取

class Order(models.Model):
    # 订单号  # uid  # 收货信息
    # 商品信息  # 总价  # 状态 0  1 2 3
    # 创建时间  # 支付时间
    uid=models.ForeignKey('Users',on_delete=models.CASCADE)#用户id  当做外键  用来联系用户类
    username=models.CharField(max_length=10)#收货人姓名
    phone=models.CharField(max_length=11)#收货人电话
    address=models.CharField(max_length=100)#收获人地址
    totalprice=models.DecimalField(max_digits=7,decimal_places=2)#此次购买物品的总价
    # 0未支付  1 已支付  2已发货  3已收货 4已取消
    status=models.IntegerField(default=0)#订单状态
    ordertime=models.DateTimeField(auto_now_add=True)#创建订单的时间
    paytime=models.DateTimeField(null=True)#支付时间
#自定义订单权限
    class Meta:
        permissions = (
            ("show_Order", "查看订单列表"),
            ("create_Order", "添加订单"),
            ("edit_Order", "修改订单"),
            ("remove_Order", "删除订单"),
        )

class OrderItem(models.Model):
    # 订单号  商品id  商品数量 商品价格
    orderid=models.ForeignKey('Order',on_delete=models.CASCADE)#订单id  外键  用作联系订单类
    bookid=models.ForeignKey('Books',on_delete=models.CASCADE)#图书id  外键  用作联系图书id
    num=models.IntegerField()#记录购买同一种商品的数量
    price=models.IntegerField()#价格

class Address(models.Model):
    # 本身id  收货人姓名  电话   收货地址 
    # 会员id   是否默认  是否删除  
    username=models.CharField(max_length=30)#收货人姓名
    phone=models.CharField(max_length=11)#收货人电话
    user_address=models.CharField(max_length=200)#收货人地址
    uid=models.ForeignKey('Users',on_delete=models.CASCADE)#会员ID  外键 用来联系会员ID 
    isdefault=models.CharField(max_length=1,default=0)#0不默认  1默认  是否默认
    isdel=models.CharField(max_length=1,default=0)  #0否  1删除  是否删除







    

    

web/myhome/models.py
from django.db import models

# Create your models here.

web/myhome/views/AddressViews.py
from django.shortcuts import render,HttpResponse,reverse
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from myadmin import models
from .IndexViews import typecom

# 添加收货地址
@csrf_exempt 
def addaddress(request):
    #获取数据
    data=request.GET.dict()
    # 收货地址表里有 收货人姓名  电话  地址  会员id   
    userobj=models.Users.objects.get(id=request.session["User"]["id"])
    if not data["name"].isalpha():
        return JsonResponse({'code':2,'msg':'添加失败,用户名应该是以字母或汉字组成'})
    if not data["address"].isalpha():
        return JsonResponse({'code':3,'msg':'添加失败,地址应该是以字母或汉字组成'})
    num=userobj.address_set.filter(user_address=data["address"],username=data["name"]).count()
    if not num:
        addressdata={
            'username':data["name"],
            'phone':data["phone"],
            'user_address':data["address"],
            'uid':userobj
        }
        addressobj=models.Address(**addressdata)
        addressobj.save()
        print(data)
        return JsonResponse({'code':0,'msg':'添加成功'})
    else:
        return JsonResponse({'code':1,'msg':'添加失败,您已经有一个相同的地址了'})

# 删除收货地址
def deladdress(request):
    try:
        id=request.GET.get("id")
        addressobj=models.Address.objects.get(id=id)
        addressobj.delete()
        return JsonResponse({'code':0,'msg':'删除成功'})
    except:
         return JsonResponse({'code':1,'msg':'删除失败'})


def modiaddress(request):
    pass

web/myhome/views/CartViews.py
from django.shortcuts import render,HttpResponse,reverse
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from myadmin import models
from .IndexViews import typecom,usercom


#购物车列表页视图
def index(request):
    context={'typelist':typecom(),'userinfo':usercom(request)}
    return render(request,'myhome/cart/index.html',context)

@csrf_exempt 
def addcart(request):
    data=request.POST.dict()
    #判断在购物车里这个用户下有没有这个商品
    uid=request.session["User"]["id"]
    # 如果有，就数量加1
    try:
        userobj=models.Users.objects.get(id=uid)
        bookobj=models.Books.objects.get(id=data["bookid"])
        cartobj=userobj.cart_set.filter(bookid=bookobj)
        if cartobj:
            cartobj[0].num+=int(data["num"])
            cartobj[0].save()          
        else:
        # 如果没有，就在购物车里增加这个用户下的这个商品
            cartdata={
                'uid':userobj,
                'bookid':bookobj,
                'num':data["num"]
            }
            cartobj=models.Cart(**cartdata)
            cartobj.save()
        return JsonResponse({'code':0,'msg':'添加成功'})
    except:
        return JsonResponse({'code':1,'msg':'添加失败'})


def delcart(request):
    try:
        bookid=request.GET.get("bookid")
        bookobj=models.Books.objects.get(id=bookid)
        userobj=models.Users.objects.get(id=request.session["User"]["id"])
        cartobj=userobj.cart_set.get(bookid=bookobj)
        cartobj.delete()
        return JsonResponse({'code':0,'msg':'删除成功'})
    except:
        return JsonResponse({'code':1,'msg':'删除失败'})

def modicart(request):
    try:
        data=request.GET.dict()
        userobj=models.Users.objects.get(id=request.session["User"]["id"])
        cartobj=userobj.cart_set.get(bookid=data["bookid"])
        cartobj.num=data["num"]
        cartobj.save()
        return JsonResponse({'code':0,'msg':'更新成功'})
    except:
         return JsonResponse({'code':1,'msg':'更新失败'})

web/myhome/views/IndexViews.py
from django.shortcuts import render,HttpResponse,reverse
from myadmin import models
from django.core.paginator import Paginator
from django.db.models import Q

import random
#导航中的分类及其对应的子类
def typecom():
    #找出顶级分类
    typelist=models.Booktype.objects.filter(pid=0)
    #循环顶级分类，找出子类，给顶级分类定义一个新的属性，用来寻找对应的子类
    for i in typelist:
        i.sub=models.Booktype.objects.filter(pid=i.id)
    return typelist
def usercom(request):
    userobj=models.Users.objects.get(id=request.session["User"]["id"])
    return userobj

#首页视图
def index(request):
    booklist=models.Books.objects.all()
    context={'typelist':typecom(),'booklist':booklist}
    return render(request,'myhome/index.html',context)

#列表页
def booklist(request,typeid):

    #根据分类id得到分类对象
    typeobj=models.Booktype.objects.get(id=typeid)
    #判断是不是顶级分类，
    if typeobj.pid==0:
        #如果是查询其所对应的所有的子类
        typeobj.sub=models.Booktype.objects.filter(pid=typeobj.id)
        typeobj.parent=typeobj.catename
    else:
        #如果不是，直接把对象赋给定义的属性，然后根据属性在模板直接查询其所对应的图书
        typeobj.sub=models.Booktype.objects.filter(pid=typeobj.pid)
        typeobj.parent=models.Booktype.objects.get(id=typeobj.pid).catename
    bidlist=[]
    for i in range(3):
        res=random.randrange(1,models.Books.objects.all().count())
        bidlist.append(res+50)
    print(bidlist)
    booklist=models.Books.objects.filter(id__in=bidlist)

   
    context={'typelist':typecom(),'list_detail':typeobj,'booklist':booklist}
    return render(request,'myhome/list.html',context)

#详情页
def detail(request,bookid):
    bookobj=models.Books.objects.get(id=bookid)
    booklist=models.Books.objects.all().exclude(id=bookid)
    
    context={'typelist':typecom(),'bookinfo':bookobj,'booklist':booklist}
    return render(request,'myhome/bookdetails.html',context)

#搜索图书
def booksearch(request):
    keywords=request.POST.get("keywords",'')
    bookob=models.Books.objects.all().exclude(isdel="004002")
    bookob=bookob.filter(
        Q(bookname__contains=keywords)|
        Q(author__contains=keywords)|
        Q(publisher__contains=keywords)|
        Q(price__contains=keywords)|
        Q(num__contains=keywords)
    )
    if not bookob:
        return HttpResponse("<script>alert('很抱歉没有您要搜索的内容，请重新输入！！！');location.href='/'</script>")
     # 实例化分页类    参数一数据集  参数二  每一显示的条数
    print(bookob)
    p = Paginator(bookob,5)
	# 获取当前的页码数
    pageindex =request.GET.get('page',1)
    # 获取当前页的数据
    booklist = p.page(pageindex)
    # 获取所有页码
    # pages = p.page_range
    # 获取总页数
    pages = p.num_pages
    context={'typelist':typecom(),'booklist':booklist,'page':pages}
    return render(request,'myhome/search.html',context)

web/myhome/views/LoginViews.py
from django.shortcuts import render,HttpResponse,reverse
from django.contrib.auth.hashers import check_password, make_password
from myadmin import models
from .IndexViews import typecom,usercom

# Create your views here.

def login(request):
    context={'typelist':typecom()}
    return render(request,'myhome/login/login.html',context)

def dologin(request):
    data=request.POST.dict()
    data.pop("csrfmiddlewaretoken")

    nextpath=request.GET.get('nextpath','/')
    if not  nextpath:
        nextpath='/' 
    obj=models.Users.objects.filter(phone=data["phone"])
    if not obj.count():
        return HttpResponse("<script>alert('手机号错误');history.back()</script>")
    if not check_password(data["password"],obj[0].password):
        return HttpResponse("<script>alert('密码错误');history.back()</script>")
    else:
        request.session['User']={'id':obj[0].id,'phone':obj[0].phone}
        url=reverse('myhome_index')
        return HttpResponse(f"<script>alert('登录成功');location.href='{nextpath}'</script>")

def logout(request):
#   del  request.session["AdminUser"]
    # request.session.AdminUser=''
    try:
        request.session.flush()
        url=reverse('myhome_login')
        info="注销成功，请登录"
    except:
        info="注销不成功，请重新注销"
        url=reverse('myhome_index')
    return HttpResponse(f"<script>alert('{info}');location.href='"+url+"'</script>")

web/myhome/views/RegisterViews.py
from django.shortcuts import render,reverse
from django.http import HttpResponse,JsonResponse
from django.contrib.auth.hashers import check_password, make_password
from myadmin import models
import requests,random
from .IndexViews import typecom,usercom
# Create your views here.

def register(request):
    context={'typelist':typecom()}
    return render(request,'myhome/login/register.html',context)


def doregister(request):
    data={}
    # 验证验证码
    vcode=request.POST.get("vcode")
    data["phone"]=request.POST.get("phone")
    if (data["phone"]==request.session["msgcode"]["phone"]) and (vcode==request.session["msgcode"]["vcode"]):
        data["password"]=request.POST.get("password")
        data['password']= make_password(data['password'], None, 'pbkdf2_sha256')
        try:
            obj=models.Users(**data)
            obj.save()
            url=reverse('myhome_login')
            return HttpResponse(f"<script>alert('恭喜你，注册成功');location.href='{url}'</script>")
        except:
            url=reverse('myhome_register')
            return HttpResponse(f"<script>alert('注册失败请重新注册');location.href='{url}'</script>")
    else:
        url=reverse("myhome_register")
        return HttpResponse(f"<script>alert('手机号或验证码出错');location.href='"+url+"'</script>")

def checkphone(request):
    phone=request.GET.get('phone')
    num=models.Users.objects.filter(phone=phone).count()
    if num:
       return JsonResponse({'code':1,'msg':'手机号已存在'})
    else:
        return JsonResponse({'code':0,'msg':'手机号可注册'})

def sendphone(request):
    phone=request.GET.get('phone')
    vcode=str(random.randint(10000,99999))
    request.session['msgcode']={'vcode':vcode,'phone':phone}
    if SendCode(phone,vcode):
        return JsonResponse({'code':0,'msg':'短信已发送，请注意查收','vcode':vcode})
    else:
        return JsonResponse({'code':1,'msg':'短信验证码发送失败','vcode':vcode})

# #发送请求给发送验证码的网站，然后获取
# def sendcode(phone,vcode):
#     url='http://106.ihuyi.com/webservice/sms.php?method=Submit'
#     text='您的验证码是：'+vcode+'。请不要把验证码泄露给其他人。'
#     data= {
#         'account':'C57099558',
#         'password':'4953e63f47bc4cdcd6ddf02aeca62482',
#         'mobile':phone,
#         'content':text,
#         'format':'json'
#         }
#     res=requests.post(url=url,data=data)
#     res=res.json()
#     print(res)
#     # {'code': 2, 'msg': '提交成功', 'smsid': '15718313248346759898'}
#     if res["code"]==2 and res["msg"]=='提交成功':
#         return True
#     else:
#         return False


def SendCode(phone,vcode):
	url = 'https://open.ucpaas.com/ol/sms/sendsms'
	data = {
			'sid':'4c0064b5f77af9da37fb74145594092e',
			'token':'1db32087f3b4111610f753a4ded823c1',
			'appid':'328129a7423b4bf595bc4435e80f8e1c',
			'templateid':'510851',
			'param':vcode,
			'mobile':phone
		}
	headers = {
			'Content-Type':'application/json'
	}

	response = requests.post(url,json=data,headers=headers)

	res = response.json()

	if res['code'] == '00000' and res['msg'] == 'OK':
		return True
	else:
		return False

web/templates/myhome/search.html
{% extends 'myhome/base.html'%}
{% block title%}
<title>图书搜索页</title>
{% endblock %}
{% block con %}
    <!-- breadcrumbs-area-start -->
    <div class="breadcrumbs-area mb-70">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumbs-menu">
                        <ul>
                            <li><a href="/">首页</a></li>
                            <li><a  class="active">图书搜索详情页</a></li>
                        </ul>
                    </div>
                </div> 
            </div>
        </div>
    </div><!-- breadcrumbs-area-end -->
    <!-- shop-main-area-start -->
    <div class="shop-main-area mb-70">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12">
                    <div class="shop-left">
                        <div class="left-title mb-20">
                            <h4>随机商品</h4>
                        </div>
                        <div class="random-area mb-30">
                            <div class="product-active-2 owl-carousel">
                                {% for i in book %}
                                <div class="product-total-2">
                                    <div class="single-most-product bd mb-18">
                                        <div class="most-product-img"><a href="{% url 'myhome_bookdetail' i.id  %}"><img src="/{{ i.bookimgs_set.first.img_url }}"  alt="book" /></a></div>
                                        <div class="most-product-content">
                                            <div class="product-rating">
                                                <ul>
                                                    <li><a href="#"><i class="fa fa-star"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-star"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-star"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-star"></i></a></li>
                                                    <li><a href="#"><i class="fa fa-star"></i></a></li>
                                                </ul>
                                            </div>
                                            <h4><a href="{% url 'myhome_bookdetail' i.id %}">{{ i.bookname }}</a></h4>
                                            <div class="product-price">
                                                <ul>
                                                    <li>¥{{ i.price }}</li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-9 col-md-9 col-sm-8 col-xs-12">
                   
                    <div class="toolbar mb-30">
                        <div class="shop-tab">
                            <div class="tab-3">
                                <ul>
                                    <li  class="active"><a href="#list" data-toggle="tab"><i class="fa fa-bars"></i>列表</a></li>
                                    <li><a href="#th" data-toggle="tab"><i class="fa fa-th-large"></i>网格</a></li>
                                   
                                </ul>
                            </div>
                            <div class="list-page">
                                <p>Items 1-9 of 11</p>
                            </div>
                        </div>
                        <div class="field-limiter">
                            <div class="control"><span>Show</span><!-- chosen-start --><select data-placeholder="Default Sorting" style="width:50px;" class="chosen-select" tabindex="1">
                                    <option value="Sorting">1</option>
                                    <option value="popularity">2</option>
                                    <option value="rating">3</option>
                                    <option value="date">4</option>
                                </select><!-- chosen-end -->
                            </div>
                        </div>
                        <div class="toolbar-sorter"><span>Sort By</span><select id="sorter" class="sorter-options" data-role="sorter">
                                <option selected="selected" value="position">Position</option>
                                <option value="name">Product Name</option>
                                <option value="price">Price</option>
                            </select><a href="#"><i class="fa fa-arrow-up"></i></a></div>
                    </div><!-- tab-area-start -->
                    <div class="tab-content">
                        <div class="tab-pane active" id="list">
                            {% for v in booklist %}
                            <div class="single-shop mb-30">
                                <div class="row">
                                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                                        <div class="product-wrapper-2">
                                            <div class="product-img">
                                                <a href="{% url 'myhome_bookdetail' v.id %}">
                                                    <img src="/{{ v.bookimgs_set.first.img_url }}"  alt="book" class="primary" />
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
                                        <div class="product-wrapper-content">
                                            <div class="product-details">
                                                <div class="product-rating">
                                                    <ul>
                                                        <li><a href="#"><i class="fa fa-star"></i></a></li>
                                                        <li><a href="#"><i class="fa fa-star"></i></a></li>
                                                        <li><a href="#"><i class="fa fa-star"></i></a></li>
                                                        <li><a href="#"><i class="fa fa-star"></i></a></li>
                                                        <li><a href="#"><i class="fa fa-star"></i></a></li>
                                                    </ul>
                                                </div>
                                                <h4><a href="{% url 'myhome_bookdetail' v.id %}">{{ v.bookname }}</a></h4>
                                                <div class="product-price">
                                                    <ul>
                                                        <li>¥{{ v.price}}</li>
                                                    </ul>
                                                </div>
                                                <p>{{ v.recommend }}</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div><!-- single-shop-end -->
                            {% endfor %}
                        </div>
                    </div><!-- tab-area-end -->
                    <!-- pagination-area-start -->
                    <div class="pagination-area mt-50">
                        <div class="page-number">
                            <ul>
                                {% load pagetag %}
                                {% PageShow page request %}
                            </ul>
                        </div>
                    </div><!-- pagination-area-end -->
                </div>
            </div>
        </div>
    </div><!-- shop-main-area-end -->
{% endblock %}