web/myadmin/urls.py
from django.contrib import admin
from django.urls import path

from .views import *
urlpatterns = [

    # path('admin/', admin.site.urls),

    #首页
    path('', IndexViews.index,name='myadmin_index'),
    
    #登录
    path('login', IndexViews.mylogin,name='myadmin_login'),
    #执行登录
    path('dologin', IndexViews.dologin,name='myadmin_dologin'),
    #验证码地址
    path('yzm', IndexViews.verifycode,name='myadmin_yzm'),

    #注销
    path('cancel', IndexViews.cancel,name='myadmin_cancel'),

    #用户管理
    path('user/index', UserViews.index,name='myadmin_user_index'),
    path('user/add', UserViews.adduser,name='myadmin_user_add'),
    path('user/del/<int:id>', UserViews.deluser,name='myadmin_user_del'),
    path('user/mod', UserViews.moduser,name='myadmin_user_mod'),

    #图书类别管理
    path('type/index', TypeViews.index,name='myadmin_type_index'),
    path('type/add', TypeViews.add,name='myadmin_type_add'),
    path('type/insert', TypeViews.insert,name='myadmin_type_insert'),
    path('type/delete', TypeViews.delete,name='myadmin_type_delete'),
    path('type/edit', TypeViews.edit,name='myadmin_type_edit'),

    #图书管理
    path('book/index', BookViews.index,name='myadmin_book_index'),
    path('book/add', BookViews.add,name='myadmin_book_add'),
    path('book/insert', BookViews.insert,name='myadmin_book_insert'),
    path('book/delete', BookViews.delete,name='myadmin_book_delete'),
    path('book/edit', BookViews.edit,name='myadmin_book_edit'),
    path('book/update', BookViews.update,name='myadmin_book_update'),

     #订单管理
    path('order/index', OrderViews.index,name='myadmin_order_index'),
    # path('order/edit', OrderViews.editorder,name='myadmin_order_edit'),
    


    #权限管理
    
    #管理员管理
    path('auth/user/index', IndexViews.authuser_index,name='myadmin_authuser_index'),
    path('auth/user/add', IndexViews.authuser_add,name='myadmin_authuser_add'),
    path('auth/user/insert', IndexViews.authuser_insert,name='myadmin_authuser_insert'),
    path('auth/user/del/<int:id>', IndexViews.authuser_del,name='myadmin_authuser_del'),
    path('auth/user/edit', IndexViews.authuser_edit,name='myadmin_authuser_edit'),



    ##组管理
    path('auth/group/index', IndexViews.authgroup_index,name='myadmin_authgroup_index'),
    path('auth/group/add', IndexViews.authgroup_add,name='myadmin_authgroup_add'),
    path('auth/group/insert', IndexViews.authgroup_insert,name='myadmin_authgroup_insert'),
    path('auth/group/del/<int:id>', IndexViews.authgroup_del,name='myadmin_authgroup_del'),
    path('auth/group/edit', IndexViews.authgroup_edit,name='myadmin_authgroup_edit'),


]

web/web/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    #特有的后台地址
    # path('admin/', admin.site.urls),
    #后台
    path('myadmin/', include('myadmin.urls')),
    #前台
    path('', include('myhome.urls')),
    #富文本编辑器
    path('ueditor/', include('ueditor.urls')),
]

web/myadmin/models.py
from django.db import models

# Create your models here.

#会员类 包括前台用户所有的信息
class Users(models.Model):
    #主要信息
    phone=models.CharField(max_length=11,unique=True)#s手机号
    password=models.CharField(max_length=80)#密码
    face=models.CharField(max_length=100,default="/static/myadmin/assets/img/user06.png")#头像
    #次要信息
    nickname=models.CharField(max_length=20,null=True)#昵称
    homeaddress=models.CharField(max_length=100,null=True)#居住地
    sex=models.CharField(max_length=6,null=True)#性别
    usertype=models.CharField(max_length=1,null=True)#身份类别
    createtime=models.DateTimeField(auto_now_add=True)#创建时间
    isdel=models.CharField(max_length=10,default='004001')#是否删除
    #自定义用户权限
    class Meta:
        permissions = (
            ("show_Users", "查看用户列表"),
            ("create_Users", "添加用户"),
            ("edit_Users", "修改用户"),
            ("remove_Users", "删除用户"),
        )

#图书分类类
class Booktype(models.Model):
    catename=models.CharField(max_length=20)#分类名
    pid=models.IntegerField()#父级id
    path=models.CharField(max_length=50)#path路径
#自定义商品分类权限
    class Meta:
        permissions = (
            ("show_Booktype", "查看图书分类列表"),
            ("create_Booktype", "添加图书分类"),
            ("edit_Booktype", "修改图书分类"),
            ("remove_Booktype", "删除图书分类"),
        )

#图书类
class Books(models.Model):
    typeid=models.ManyToManyField(to="Booktype")#图书类别id 用作外键联系类别类
    bookname=models.CharField(max_length=70) #图书名称
    recommend=models.CharField(max_length=255,null=True) #推荐语
    author=models.CharField(max_length=50) #作者
    publisher=models.CharField(max_length=150) #出版社
    pdate=models.DateField() #出版时间
    price=models.DecimalField(max_digits=5,decimal_places=2) #价格
    num=models.IntegerField()#库存
    isbn=models.CharField(max_length=13)# 国际书号isbn
    bookdetail=models.TextField(null=True) #商品详情
    cate=models.CharField(max_length=1,default='0') #0上架 1热卖 2促销  3推荐 4下架
    isdel=models.CharField(max_length=6,default="004001") #是否逻辑删除  004001可用  004002不可用
#自定义图书权限
    class Meta:
        permissions = (
            ("show_Books", "查看图书列表"),
            ("create_Books", "添加图书"),
            ("edit_Books", "修改图书"),
            ("remove_Books", "删除图书"),
        )

##图集
class Bookimgs(models.Model):
    img_url=models.ImageField(upload_to="static/myadmin/book_img/")#图书图片地址
    bookid=models.ForeignKey('Books',on_delete=models.CASCADE)#图书id  用来联系图书类


#购物车
class Cart(models.Model):
    #用户ID
    # 商品id
    # 数量
    # 是否选中
    uid=models.ForeignKey('Users',on_delete=models.CASCADE) #会员id  当做外键  用来联系用户类
    bookid=models.ForeignKey('Books',on_delete=models.CASCADE)#图书id 当做外键  用来联系图书类
    num=models.IntegerField()#图书商品的数量
    select=models.IntegerField(default=0)#0未选中  1选中
    # 前端业务的数据是可以被修改的，所以前端价格不能获取，展出的数据不一定真，能用id获取就不要用其他地方获取

class Order(models.Model):
    # 订单号  # uid  # 收货信息
    # 商品信息  # 总价  # 状态 0  1 2 3
    # 创建时间  # 支付时间
    uid=models.ForeignKey('Users',on_delete=models.CASCADE)#用户id  当做外键  用来联系用户类
    username=models.CharField(max_length=10)#收货人姓名
    phone=models.CharField(max_length=11)#收货人电话
    address=models.CharField(max_length=100)#收获人地址
    totalprice=models.DecimalField(max_digits=7,decimal_places=2)#此次购买物品的总价
    # 0未支付  1 已支付  2已发货  3已收货 4已取消
    status=models.IntegerField(default=0)#订单状态
    ordertime=models.DateTimeField(auto_now_add=True)#创建订单的时间
    paytime=models.DateTimeField(null=True)#支付时间
#自定义订单权限
    class Meta:
        permissions = (
            ("show_Order", "查看订单列表"),
            ("create_Order", "添加订单"),
            ("edit_Order", "修改订单"),
            ("remove_Order", "删除订单"),
        )

class OrderItem(models.Model):
    # 订单号  商品id  商品数量 商品价格
    orderid=models.ForeignKey('Order',on_delete=models.CASCADE)#订单id  外键  用作联系订单类
    bookid=models.ForeignKey('Books',on_delete=models.CASCADE)#图书id  外键  用作联系图书id
    num=models.IntegerField()#记录购买同一种商品的数量
    price=models.IntegerField()#价格

class Address(models.Model):
    # 本身id  收货人姓名  电话   收货地址 
    # 会员id   是否默认  是否删除  
    username=models.CharField(max_length=30)#收货人姓名
    phone=models.CharField(max_length=11)#收货人电话
    user_address=models.CharField(max_length=200)#收货人地址
    uid=models.ForeignKey('Users',on_delete=models.CASCADE)#会员ID  外键 用来联系会员ID 
    isdefault=models.CharField(max_length=1,default=0)#0不默认  1默认  是否默认
    isdel=models.CharField(max_length=1,default=0)  #0否  1删除  是否删除







    

    

web/myadmin/views/BookViews.py
from django.shortcuts import render,reverse
from django.http import HttpResponse,JsonResponse
from django.contrib.auth.decorators import permission_required
from django.core.paginator import Paginator
from django.db.models import Q
from .. import models
from .import TypeViews
import re,os

# Create your views here.
#查看图书视图
@permission_required('myadmin.show_Books',raise_exception=True)
def index(request):
    ##接收参数
    keywords=request.GET.get("keywords",'')
    keywords=keywords.strip()
    fieldname=request.GET.get("fieldname",None)
    ob=models.Books.objects.all().exclude(isdel="004002")
    if fieldname:
        if fieldname=='all':
            if keywords:
               
                ob=ob.filter(
                    Q(bookname__contains=keywords)|
                    Q(author__contains=keywords)|
                    Q(publisher__contains=keywords)|
                    Q(price__contains=keywords)|
                    Q(num__contains=keywords)
                )
        else:
            search={fieldname+'__contains':keywords}
            ob=ob.filter(**search)
    # 实例化分页类    参数一数据集  参数二  每一显示的条数
    p = Paginator(ob,5)
	# 获取当前的页码数
    pageindex =request.GET.get('page',1)
    # 获取当前页的数据
    booklist = p.page(pageindex)
    # 获取所有页码
    # pages = p.page_range
    # 获取总页数
    pages = p.num_pages
    context={'booklist':booklist,'page':pages,'fieldname':fieldname,'keywords':keywords}
    return render(request,'myadmin/books/index.html',context)

#添加视图
@permission_required('myadmin.create_Books',raise_exception=True)
def add(request):
    data=models.Booktype.objects.extra(select={'paths':'concat(path,id)'}).order_by("paths")
    types=TypeViews.selectAlltype(data)
    return render(request,'myadmin/books/addbook.html',{'typelist':types})

@permission_required('myadmin.create_Books',raise_exception=True)
def insert(request):
   
    # 获取表单的内容
    data=request.POST.dict()
    data.pop("csrfmiddlewaretoken")
    # 弹出typeid，因为分类与图书的关系是多对多，所以他们的关系存在另外一张表里
    data.pop("typeid")
    #获取图书的图片集合
    try:
        imglist=request.FILES.getlist("pics")
        if len(imglist)!=3:
            data.pop("pics")
        #获取对应的所属分类id ，然后存入相应的表里，多对多的关系
        typeid=request.POST.getlist("typeid")
        if not typeid:
            return HttpResponse(f"<script>alert('请为选择分类项');location.href='{url}''</script>")
        if not data["recommend"]:
            data.pop("recommend")
        if not re.findall('^\d+?\.\d{2}$',data["price"]):
            return HttpResponse(f"<script>alert('请输入有效的售价');location.href='{url}'</script>")
        if not re.findall('\d{13}',data["isbn"]):
            return HttpResponse(f"<script>alert('请输入有效的国际书号');location.href='{url}'</script>")
        if not  re.findall('\d',data["num"]):
            return HttpResponse(f"<script>alert('请输入有效的库存数量');location.href='{url}'</script>")

        ##创建书籍对象，完成添加，获取图书的对象
        obj=models.Books(**data)
        obj.save()


        #根据获取的id得到分类模型里的对象，然后存入多对多的关系里
        typeobjs=models.Booktype.objects.filter(id__in=typeid)
        ##给书籍和分类设置关系，必须是在对象保存之后才能在多对多的表里面添加对应的分类的关系
        obj.typeid.set(typeobjs)
    
        # 判断是否上传了图片，如果上传了，就删除文件夹中的就图片，没上传，就不用删除
        if imglist:
            for i in imglist:
                img_obj=models.Bookimgs()
                img_obj.bookid=obj
                img_obj.img_url=i
                img_obj.save()
                url=reverse('myadmin_book_index')
            return HttpResponse(f"<script>alert('添加成功');location.href='{url}'</script>")
        else:
            url=reverse("myadmin_book_add")
            return HttpResponse(f"<script>alert('请为书籍添加一张或多张封面图');location.href='{url}';</script>")
    except:
        url=reverse("myadmin_book_add")
        return HttpResponse(f"<script>alert('操作异常，请稍后再试！！！');location.href='{url}';</script>")
  
@permission_required('myadmin.remove_Books',raise_exception=True)
def delete(request):
    id=request.GET.get("id")
    obj=models.Books.objects.get(id=id)
    #先删除对应文件夹里的图片，然后删除对应关系，最后删除图书商品
    for i in obj.bookimgs_set.all():
        os.remove(i.img_url.path)
    #删除对应的分类关系
    obj.delete()

    # data.isdel="004002"
    # data.save()
    return JsonResponse({"code":0,"msg":"删除成功"})

@permission_required('myadmin.edit_Books',raise_exception=True)
def edit(request):
    id=request.GET.get("id")
    data=models.Books.objects.get(id=id)
    return render(request,'myadmin/books/editbook.html',{'bookinfo':data})

@permission_required('myadmin.edit_Books',raise_exception=True)
def update(request):
    #获取图片数据
    data=request.POST.dict()
    data.pop("csrfmiddlewaretoken")
    # 处理图片
    # 判断是否上传了图片，如果上传了，就删除文件夹中的就图片，没上传，就不用删除
    try:
        img_url=request.FILES.get('img_url',None)
        # 用户上传了图片
        if img_url:
            url='./'+data["old_img_url"]
            if data["old_img_url"]:
                os.remove(url)
            obj=models.Books.objects.get(id=data["id"])
            imgxx={'img_url':data["old_img_url"],'bookid':obj}
            #查询旧图片在表里所对应的删除，然后删除
            img_obj=models.Bookimgs.objects.filter(**imgxx)
            img_obj.delete()
            # 实例化一个图书图集对象，在图集类里添加用户上传的新的图片，然后保存
            img_obj=models.Bookimgs()
            img_obj.bookid=obj
            img_obj.img_url=img_url
            img_obj.save()
        else:
            data.pop("img_url")
        data.pop("old_img_url")
        
        # 处理图书的数据,更新已修改的数据
        if not data["recommend"]:
            data.pop("recommend")
        if re.findall('^\d+?\.\d{2}$',data["price"]):
            if re.findall('\d{13}',data["isbn"]):
                ob=models.Books.objects.filter(id=data["id"]).update(**data)
                info='修改成功'
                url=reverse('myadmin_book_index')     
                return HttpResponse(f"<script>alert('{info}');location.href='"+url+"';</script>")
        else:
            info='修改失败，请输入有效的值'
            url=reverse('myadmin_book_edit')
            id=str(data["id"])
            return HttpResponse(f"<script>alert('{info}');location.href='{url}?id={id}';</script>")
    except:
        url=reverse('myadmin_book_edit')
        id=str(data["id"])
        return HttpResponse(f"<script>alert('程序异常，请稍后再试！！！');location.href='{url}?id={id}';</script>")
  

web/myadmin/views/OrderViews.py
from django.shortcuts import render,HttpResponse
from .. import models

# Create your views here.

def index(request):
    orderdata=models.Order.objects.all()
    context={'orderdata':orderdata}
    return render(request,'myadmin/order/index.html',context)

web/templates/myadmin/order/index.html
{% extends 'myadmin/base.html' %}
{% block title%}
<title>订单列表</title>
{% endblock %}
{% block con%}
<div class="row-content am-cf">
    <div class="row  am-cf">
            <div class="am-u-sm-12 am-u-md-12 am-u-lg-12">
                    <div class="widget am-cf">
                        <div class="widget-head am-cf">
                            <div class="widget-title  am-cf">订单列表</div>
                        </div>
                        <div class="widget-body  am-fr">
                            

                            <div class="am-u-sm-12">
                                {% for i in orderdata %}
                                <table  width="100%" style="background: silver;border: 1px solid black;"  class="am-table am-table-compact am-table-striped tpl-table-black ">
                                    <thead>
                                        <tr>
                                            <th colspan="2" style="text-align: left;">
                                                订单时间：{{ i.ordertime }}
                                                &nbsp;&nbsp;&nbsp;&nbsp;
                                                订单号:{{ i.id }}
                                            </th>
                                            <th style="text-align: center;">
                                                    订单总价：¥{{ i.totalprice }}&nbsp;&nbsp;&nbsp;&nbsp;
                                                    <!-- # 0未支付  1 已支付  2已发货  3已收货 4已取消 -->
                                                    订单状态：
                                                    {% if i.status == 0 %}
                                                    未支付
                                                    {% elif i.status == 1 %}
                                                    已支付
                                                    {% elif i.status == 2 %}
                                                    已发货
                                                    {% elif i.status == 3 %}
                                                    已收货
                                                    {% elif i.status == 4 %}
                                                    已取消
                                                    {% endif %}

                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for ii in i.orderitem_set.all %}
                                        <tr class="gradeX" style="text-align: center;">
                                            <td>
                                                <img style="width: 70%;" src="/{{ ii.bookid.bookimgs_set.first.img_url }}"  class="tpl-table-line-img" alt="">
                                            </td>
                                            <td class="am-text-middle">
                                                {{ ii.bookid.bookname }}×{{ii.num}}
                                            </td>
                                            {% load pagetag %}
                                            <td class="am-text-middle">
                                                    ¥{% cheng ii.bookid.price ii.num %}
                                            </td>
                                        </tr>
                                        {% endfor %}
                                        <!-- more data -->
                                    </tbody>
                                </table>
                                {% endfor %}
                            </div>
                            <div class="am-u-lg-12 am-cf">

                                <div class="am-fr">
                                    <ul class="am-pagination tpl-pagination">
                                           
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
    </div>
</div>
{% endblock %}